apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dental-cluster
  region: us-east-1

nodeGroups:
  - name: dental-nodes
    instanceType: t3.small
    desiredCapacity: 2
    iam:
      instanceRoleARN: arn:aws:iam::813554192509:role/EKSNodeRole
