apiVersion: apps/v1
kind: Deployment
metadata:
  name: dental-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dental-backend
  template:
    metadata:
      labels:
        app: dental-backend
    spec:
      containers:
        - name: dental-backend
          image: smiledental/dental-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              value: mongodb+srv://jmUser:4E7TlepxPZ6pITg9@cluster.mkyvzka.mongodb.net/?retryWrites=true&w=majority&appName=Cluster
            - name: JWT_SECRET
              value: my_super_secret_key
